version: '3'
networks:
  crazy-day.net:
    driver: bridge

services:

  crazy.db:
    image: 'mariadb:latest'
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci'
    env_file: ./crazy.env
    ports:
      - '3306:3306'
    networks:
      - crazy-day.net
    volumes:
      - ./src/sql:/var/sql

  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - '8080:8080'
    networks:
      - crazy-day.net