version: '3'
networks:
  crazy-day.net:
    driver: bridge

services:
  directus:
    image: directus/directus:latest
    ports:
      - 61501:8055
    volumes:
      - ./database:/database
      - ./uploads:/uploads
      - ./extensions:/extensions
    restart: on-failure
    env_file:
      - ./config/.env.directus
    depends_on:
      - directus.db
    networks:
      - crazy-day.net

  directus.db:
    image: postgres:latest
    volumes:
      - ./database_data:/var/lib/postgresql/data
    env_file:
      - ./config/.env.database
    networks:
      - crazy-day.net